README.md
=> added a sentence to READ.E.MD

.gitignore
Adds directories in MVC format
=> add directories

db/schema.sql
adds starter files to directories
=> adds MVC directories and starter files

config/connection.js, models/Event.js, models/Item.js, models/User.js, models/index.js, package-lock.json, package.json
Adds models, associations, and the package.json file
=> adds models, associations, and package files

models/Item.js, package.json, seeds/Event-seeds.js, seeds/Item-seeds.js, seeds/User-seeds.js, seeds/seed.js
Had to fix Item model with this push.
=> adds seeds, fixes Item, adds scripts to package json

controllers/api/index.js, controllers/homeRoutes.js, controllers/index.js, models/index.js, server.js, utils/auth.js
Adds server, homeRoutes, and auth along with basic route framework.
=> adds server, homeRoutes, and auth, and basic routes framework

controllers/api/eventRoutes.js, controllers/api/index.js, controllers/api/itemRoutes.js, controllers/api/userRoutes.js, controllers/homeRoutes.js
Adds routes (initial pass). Will have to go back and add withAuth to the routes later one.
=> adds routes

README.md, public/event-setup.html, public/js/setup.js
had written up majority of setup.js but it was not in handlebar, cleared out. will fill out correct language later
=> linked js to html and fixed readme

controllers/api/eventRoutes.js, models/Event.js
Adds get/set statements in event model for invite emails. The post route for events wasn't working properly without this functionality.
=> adds get and set formatting for emails

views/event-setup.handlebars
Added the beginning code for event-setup.handlebars
=> Handlebars

controllers/homeRoutes.js
Ties homeRoutes to main and home
=> ties homeRoutes to front end

controllers/api/index.js, controllers/api/newEvent.js, controllers/api/userRoutes.js, controllers/homeRoutes.js, public/js/login.js, server.js, views/event-setup.handlebars, views/layouts/main.handlebars
adds event-setup route, plugs in backend to front
=> adds event-setup route, plugs in backend to front

public/js/logout.js, views/layouts/main.handlebars
=> adds logout function

controllers/api/eventRoutes.js, controllers/api/itemRoutes.js, controllers/homeRoutes.js
adds withAuth to secure endpoints
=> adds withAuth to secure endpoints

views/event-setup.handlebars
=> cleans up some code

controllers/api/eventRoutes.js, controllers/api/itemRoutes.js, public/css/style.css, public/js/add-item.js, views/add-item.handlebars, views/event-view.handlebars, views/layouts/main.handlebars, views/partials/event-home.handlebars
connects item routes, adds add-item
=> connects item routes, adds add-item

models/Event.js, seeds/Event-seeds.js
adds event location and description to event model
=> adds event location and description to event model

controllers/api/eventRoutes.js, models/Event.js, public/js/setup.js, seeds/Event-seeds.js, views/event-setup.handlebars
=> modifies event post route

controllers/api/eventRoutes.js, utils/send-emails.js
=> adds sendgrid functionality

package-lock.json, package.json, public/css/style.css, views/event-view.handlebars, views/layouts/main.handlebars
=> styles item cards

config/connection.js, server.js, utils/send-emails.js
=> changes env config order

utils/send-emails.js
=> changes env config

public/css/style.css, public/js/delete-event.js, utils/helpers.js, views/event-view.handlebars
adds delete event functionality
=> adds delete event functionality

controllers/api/eventRoutes.js, models/index.js, public/css/style.css, public/js/delete-event.js
=> odds and ends

models/Item.js
=> fixes deletion cascade

controllers/api/eventRoutes.js, public/js/delete-item.js, utils/helpers.js, views/event-view.handlebars
connects delete item functionality and makes delete button dynamic
=> connects delete item functionality and makes delete button dynamic

controllers/api/eventRoutes.js, controllers/homeRoutes.js, public/css/style.css, public/js/edit-event.js, utils/helpers.js, views/event-edit.handlebars, views/event-view.handlebars
integrates edit event functionality
=> integrates edit event functionality

public/js/delete-item.js
=> fixes delete item bug

views/event-view.handlebars
=> fixes delete button bug
